### ISSUE TITLE
gon escaping & in string

### ISSUE THREAD

**Issue by colinl** [gazay/gon#197]
Hi, is it ok to ask questions here?
I have gon working well in rails 3.2 with ruby 1.8.7 and am upgrading the app to rails 4.0 ruby 2.0.  I have updated gems appropriately (I think).
In the source I have code such as
gon.url = "path.json?var1=value1&var2=value2"
but in the html (viewed in Firefox) I see
window.gon={};gon.url="path.json?var1=value1\u0026var2=value2"
whereas in the rails 3.2 version I see
window.gon={};gon.url="path.json?var1=value1&amp;var2=value2"

Is this an expected change or am I doing something wrong?
Using rails 4.0.13,  ruby 2.0.0-p647, gon 6.0.1, json 1.8.3, multi-json 1.11.2

**Comment by takiy33** [comment]
I think that it is expected behavior.

I notice `gon.url="path.json?var1=value1\u0026var2=value2"` on inspector and `gon.url="path.json?var1=value1&var2=value2"` on web console.

Please see blow pictures.

### Inspector

<img width="691" alt="1" src="https://cloud.githubusercontent.com/assets/3800237/12072986/1f51c594-b147-11e5-84d5-b53cceca5b3f.png">

### Web console

<img width="312" alt="2" src="https://cloud.githubusercontent.com/assets/3800237/12072989/262b9f3e-b147-11e5-87e7-380267e67814.png">

Thank you.
